model {
  file: "model.sdf"
}
name: "Schleich_African_Black_Rhino"
description: "Schleich African Black Rhino"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Schleich"
}
annotations {
  key: "gtin"
  value: "04005086141933"
}
annotations {
  key: "sku"
  value: "4005086141933"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
